Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -51,14 +51,10 @@ jobs:
         with:
           name: version
           path: version.txt
-
-  build-ubuntu:
-    name: Build Ubuntu ${{ matrix.ubuntu_version }}
+  build-ubuntu-18:
+    name: Build Ubuntu 18.04
     needs: checking-build-version
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        ubuntu_version: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
+    runs-on: ubuntu-18.04
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -81,15 +77,81 @@ jobs:
           cat version/version.txt >> $GITHUB_ENV
       - name: Set Up Environment
         run: |
-          echo "Building on ${{ matrix.ubuntu_version }}"
+          echo "Building on ubuntu-18.04"
+          sudo apt-get update -y
+          sudo apt-get upgrade -y
+          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake libssl-dev
+      - name: Build Depends
+        run: |
+          echo "building with $(nproc) threads"
+          make -C depends -j$(nproc)
+      - name: Configure
+        run: |
+          ./autogen.sh
+          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
+      - name: Build Binary
+        run: |
+          make -j$(nproc) || { echo "make failed"; exit 1; }
+          mkdir -p $BUILD_DIR
+          mv src/{gspcoin-cli,gspcoin-tx,gspcoind,qt/gspcoin-qt} $BUILD_DIR/
+          strip $BUILD_DIR/*
+      - name: Generate Checksums and Compress
+        run: |
+          echo "building $BUILD_VERSION version"
+          cd $BUILD_DIR
+          shasum gspcoin-cli >> checksums.txt
+          sha256sum gspcoin-cli >> checksums.txt
+          shasum gspcoind >> checksums.txt
+          sha256sum gspcoind >> checksums.txt
+          shasum gspcoin-tx >> checksums.txt
+          sha256sum gspcoin-tx >> checksums.txt
+          shasum gspcoin-qt >> checksums.txt
+          sha256sum gspcoin-qt >> checksums.txt
+          cat checksums.txt
+          cd ..
+          tar -cvzf ${COIN_NAME}-ubuntu18-${BUILD_VERSION}.tar.gz $BUILD_DIR/*
+          mkdir -p ${COMPRESS_DIR}
+          mv ${COIN_NAME}-ubuntu18-${BUILD_VERSION}.tar.gz ${COMPRESS_DIR}/
+          shasum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu18-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          sha256sum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu18-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          cat ${COMPRESS_DIR}/checksums.txt
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.COIN_NAME }}-ubuntu18-${{ env.BUILD_VERSION }}
+          path: ${{ env.COMPRESS_DIR }}
+
+  build-ubuntu-20:
+    name: Build Ubuntu 20.04
+    needs: checking-build-version
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Getting Version
+        uses: actions/download-artifact@v4
+        with:
+          name: version
+          run_id: ${{ needs.checking-build-version.outputs.workflow_id }}
+          path: version
+      - name: Check if artifact is downloaded
+        run: |
+            if [ -f version/version.txt ]; then
+              echo "version artifact found"
+            else
+              echo "version artifact not found"
+              exit 1
+            fi
+      - name: Extract version
+        run: |
+          cat version/version.txt >> $GITHUB_ENV
+      - name: Set Up Environment
+        run: |
+          echo "Building on ubuntu-20.04"
           sudo apt-get update -y
           sudo apt-get upgrade -y
           sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
-          if [ "${{ matrix.ubuntu_version }}" == "ubuntu-18.04" ]; then
-            sudo apt-get install -y  libssl-dev
-          fi
-      - name: Patch ZMQ (Ubuntu 20.04 and 24.04)
-        if: ${{ matrix.ubuntu_version == 'ubuntu-20.04' || matrix.ubuntu_version == 'ubuntu-24.04' }}
+      - name: Patch ZMQ
         run: |
           cd depends/work/build/x86_64-pc-linux-gnu/zeromq/4.3.4-c1b1c425375
           wget https://gist.githubusercontent.com/thegokudragon/889591897b527a924b0950227e30a1b6/raw/67f4c44409e514b21544f091624a6a26f04cb70d/zmq_strncpy_fix.patch
@@ -122,18 +184,161 @@ jobs:
           sha256sum gspcoin-qt >> checksums.txt
           cat checksums.txt
           cd ..
-          tar -cvzf ${COIN_NAME}-${{ matrix.ubuntu_version }}-${BUILD_VERSION}.tar.gz $BUILD_DIR/*
+          tar -cvzf ${COIN_NAME}-ubuntu20-${BUILD_VERSION}.tar.gz $BUILD_DIR/*
           mkdir -p ${COMPRESS_DIR}
-          mv ${COIN_NAME}-${{ matrix.ubuntu_version }}-${BUILD_VERSION}.tar.gz ${COMPRESS_DIR}/
-          shasum ${COMPRESS_DIR}/${COIN_NAME}-${{ matrix.ubuntu_version }}-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
-          sha256sum ${COMPRESS_DIR}/${COIN_NAME}-${{ matrix.ubuntu_version }}-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          mv ${COIN_NAME}-ubuntu20-${BUILD_VERSION}.tar.gz ${COMPRESS_DIR}/
+          shasum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu20-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          sha256sum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu20-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
           cat ${COMPRESS_DIR}/checksums.txt
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.COIN_NAME }}-${{ matrix.ubuntu_version }}-${{ env.BUILD_VERSION }}
+          name: ${{ env.COIN_NAME }}-ubuntu20-${{ env.BUILD_VERSION }}
+          path: ${{ env.COMPRESS_DIR }}
+  build-ubuntu-22:
+    name: Build Ubuntu 22.04
+    needs: checking-build-version
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Getting Version
+        uses: actions/download-artifact@v4
+        with:
+          name: version
+          run_id: ${{ needs.checking-build-version.outputs.workflow_id }}
+          path: version
+      - name: Check if artifact is downloaded
+        run: |
+            if [ -f version/version.txt ]; then
+              echo "version artifact found"
+            else
+              echo "version artifact not found"
+              exit 1
+            fi
+      - name: Extract version
+        run: |
+          cat version/version.txt >> $GITHUB_ENV
+      - name: Set Up Environment
+        run: |
+          echo "Building on ubuntu-22.04"
+          sudo apt-get update -y
+          sudo apt-get upgrade -y
+          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
+      - name: Build Depends
+        run: |
+          echo "building with $(nproc) threads"
+          make -C depends -j$(nproc)
+      - name: Configure
+        run: |
+          ./autogen.sh
+          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
+      - name: Build Binary
+        run: |
+          make -j$(nproc) || { echo "make failed"; exit 1; }
+          mkdir -p $BUILD_DIR
+          mv src/{gspcoin-cli,gspcoin-tx,gspcoind,qt/gspcoin-qt} $BUILD_DIR/
+          strip $BUILD_DIR/*
+      - name: Generate Checksums and Compress
+        run: |
+          echo "building $BUILD_VERSION version"
+          cd $BUILD_DIR
+          shasum gspcoin-cli >> checksums.txt
+          sha256sum gspcoin-cli >> checksums.txt
+          shasum gspcoind >> checksums.txt
+          sha256sum gspcoind >> checksums.txt
+          shasum gspcoin-tx >> checksums.txt
+          sha256sum gspcoin-tx >> checksums.txt
+          shasum gspcoin-qt >> checksums.txt
+          sha256sum gspcoin-qt >> checksums.txt
+          cat checksums.txt
+          cd ..
+          tar -cvzf ${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz $BUILD_DIR/*
+          mkdir -p ${COMPRESS_DIR}
+          mv ${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz ${COMPRESS_DIR}/
+          shasum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          sha256sum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu22-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          cat ${COMPRESS_DIR}/checksums.txt
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.COIN_NAME }}-ubuntu22-${{ env.BUILD_VERSION }}
           path: ${{ env.COMPRESS_DIR }}
 
+  build-ubuntu-24:
+    name: Build Ubuntu 24.04
+    needs: checking-build-version
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Getting Version
+        uses: actions/download-artifact@v4
+        with:
+          name: version
+          run_id: ${{ needs.checking-build-version.outputs.workflow_id }}
+          path: version
+      - name: Check if artifact is downloaded
+        run: |
+            if [ -f version/version.txt ]; then
+              echo "version artifact found"
+            else
+              echo "version artifact not found"
+              exit 1
+            fi
+      - name: Extract version
+        run: |
+          cat version/version.txt >> $GITHUB_ENV
+      - name: Set Up Environment
+        run: |
+          echo "Building on ubuntu-24.04"
+          sudo apt-get update -y
+          sudo apt-get upgrade -y
+          sudo apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
+      - name: Patch ZMQ
+        run: |
+          cd depends/work/build/x86_64-pc-linux-gnu/zeromq/4.3.4-c1b1c425375
+          wget https://gist.githubusercontent.com/thegokudragon/889591897b527a924b0950227e30a1b6/raw/67f4c44409e514b21544f091624a6a26f04cb70d/zmq_strncpy_fix.patch
+          patch -p0 < zmq_strncpy_fix.patch
+      - name: Build Depends
+        run: |
+          echo "building with $(nproc) threads"
+          make -C depends -j$(nproc)
+      - name: Configure
+        run: |
+          ./autogen.sh
+          ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
+      - name: Build Binary
+        run: |
+          make -j$(nproc) || { echo "make failed"; exit 1; }
+          mkdir -p $BUILD_DIR
+          mv src/{gspcoin-cli,gspcoin-tx,gspcoind,qt/gspcoin-qt} $BUILD_DIR/
+          strip $BUILD_DIR/*
+      - name: Generate Checksums and Compress
+        run: |
+          echo "building $BUILD_VERSION version"
+          cd $BUILD_DIR
+          shasum gspcoin-cli >> checksums.txt
+          sha256sum gspcoin-cli >> checksums.txt
+          shasum gspcoind >> checksums.txt
+          sha256sum gspcoind >> checksums.txt
+          shasum gspcoin-tx >> checksums.txt
+          sha256sum gspcoin-tx >> checksums.txt
+          shasum gspcoin-qt >> checksums.txt
+          sha256sum gspcoin-qt >> checksums.txt
+          cat checksums.txt
+          cd ..
+          tar -cvzf ${COIN_NAME}-ubuntu24-${BUILD_VERSION}.tar.gz $BUILD_DIR/*
+          mkdir -p ${COMPRESS_DIR}
+          mv ${COIN_NAME}-ubuntu24-${BUILD_VERSION}.tar.gz ${COMPRESS_DIR}/
+          shasum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu24-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          sha256sum ${COMPRESS_DIR}/${COIN_NAME}-ubuntu24-${BUILD_VERSION}.tar.gz >> ${COMPRESS_DIR}/checksums.txt
+          cat ${COMPRESS_DIR}/checksums.txt
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.COIN_NAME }}-ubuntu24-${{ env.BUILD_VERSION }}
+          path: ${{ env.COMPRESS_DIR }}
 
   build-macos:
     name: macOS Build
